package main

import (
	"bytes"
	"io"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/kharljhon14/snippetbox/internal/assert"
)

func TestPing(t *testing.T) {
	// Init responser recorder
	rr := httptest.NewRecorder()

	// Init a new dummy http.Request

	r, err := http.NewRequest(http.MethodGet, "/", nil)
	if err != nil {
		t.Fatal(err)
	}

	// Call the ping handler function,
	// passing the response recorder and Request

	ping(rr, r)

	// Call the Result() method on the responseRecoder to get the
	// http response generated by the ping handler

	rs := rr.Result()

	assert.Equal(t, rs.StatusCode, http.StatusOK)

	// And we can check that the reponse body is written by the ping handler
	// equals "Ok"

	defer rs.Body.Close()

	body, err := io.ReadAll(rs.Body)
	if err != nil {
		t.Fatal(err)
	}
	bytes.TrimSpace(body)

	assert.Equal(t, string(body), "Ok")
}
